# Generated by Django 2.2.3 on 2020-04-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название покемона на русском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя покемона на английском')),
                ('title_jp', models.CharField(blank=True, max_length=20, null=True, verbose_name='имя покемона на японском')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.Pokemon', verbose_name='Из кого эволюционирует')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.FloatField(verbose_name='Широта')),
                ('Lon', models.FloatField(verbose_name='Долгота')),
                ('Appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Появится в')),
                ('Disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Исчезнет в')),
                ('Level', models.IntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('Health', models.IntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('Strength', models.IntegerField(blank=True, null=True, verbose_name='Сила')),
                ('Defence', models.IntegerField(blank=True, null=True, verbose_name='Защита')),
                ('Stamina', models.IntegerField(blank=True, null=True, verbose_name='Выносливость')),
                ('Pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon', verbose_name='Название покемона')),
            ],
        ),
    ]
