# Generated by Django 2.2.3 on 2020-11-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemonelementtype_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='image',
        ),
        migrations.AddField(
            model_name='pokemonelementtype',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка стихии'),
        ),
    ]
