# Generated by Django 2.2.3 on 2020-11-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20201118_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка стихии'),
        ),
    ]
