# Generated by Django 2.2.3 on 2020-11-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20201118_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(to='pokemon_entities.PokemonElementType', verbose_name='Силён против'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(to='pokemon_entities.PokemonElementType', verbose_name='Стихия покемона'),
        ),
    ]
